# Generated by Django 4.1.2 on 2022-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_alter_post_options_post_status_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
