# Generated by Django 4.1.2 on 2022-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_post_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='文章浏览量'),
        ),
    ]
