# Generated by Django 4.1.2 on 2022-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_remove_post_is_comment_post_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
